replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: false
    in:
      # Replace names in incoming commands
      command: false

      # Replace names in general (non-command) incoming messages
      general: false
  scoreboard: false
  scoreboardScore: false
  scoreboardTeam: false
  tabComplete:
    chat: false

updateSelf: true

random:
  join:
    nick: false
    skin: false
  nick:
  - "inventivetalent"
  - "md_5"
  - mojang: # Name category
    - "jeb_"
    - "Notch"
    - "Dinnerbone"
  skin:
  - "md_5"
  - "inventivetalent"

names:
  # Format for names, for example '&9%s' would color all names blue. Note: names can't be longer than 16 charcters and will be shortened.
  format: "%s"

  # Format for names in chat messages
  chatFormat: "%s&r"

#Enable this if this server is behind a BungeeCord server
bungeecord: false

storage:
  # Storage type
  # - temporary
  #     saves all data in memory until the server is stopped
  # - local (recommended)
  #     creates a local database or uses the database specified in bukkit.yml
  # - sql
  #     uses an SQL server
  # - redis
  #     uses a Redis server
  type: "local"
  sql:
    address: "jdbc:mysql://localhost:3306/minecraft"
    user: ""
    pass: ""
  redis:
    host: "localhost"
    port: 6379
    pass: ""
    max-connections: 4


messages:
  command:
    name:
      changed: "&aChanged &b%player%'s &aname to &b%name%&a."
      cleared: "&aCleared &b%player%'s &aname"
      list:
        used: "&eUsed names:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified name is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used names"
    skin:
      changed: "&aChanged &b%player%'s &askin to &b%skin%''s&a skin."
      cleared: "&aCleared &b%player%'s &askin"
      list:
        used: "&eUsed names:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified skin is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used skins"
    error:
      unknown: "&cUnknown error while executing command. See console for details."
      permission: "&cYou are missing the following permission: %s"
      illegalSender: "&cThis command is only available to players"
      unhandled: "&cInternal exception. See console for details."
      length:
       short: "&cMissing arguments. Usage: %s"
       long: "&cToo many arguments. Usage: %s"
      parse: "&cFailed to parse argument '%s' to %s"
      target:
        notFound: "&cPlayer could not be found"

# Disable the features below, if you're only interested in utilizing the API.
pluginFeatures:
  commands:
    general: true
    nick: true
    skin: true
