name: NickNamer
main: org.inventivetalent.nicknamer.NickNamerPlugin
author: inventivetalent
version: ${project.version}

softdepend: [PacketListenerApi]
database: true

commands:
  nicknamer:
    aliases: []